# Словарь с полным списком подкатегорий для категорий
# Ключ – код категории (например, 'stroitelstvo_remont' для "Строительство и ремонт")
# Значение – словарь, где:
#   - ключ 'all' соответствует варианту "Посмотреть все объявления в <название категории>"
#   - остальные ключи – коды подкатегорий, а значения – отображаемые названия.
SUBCATEGORY_MAPPING_FULL = {
    "stroitelstvo_remont": {
        "all": "Посмотреть все объявления в Строительство и ремонт",
        "santehnika": "Сантехника",
        "instrumenty_oborudovanie": "Инструменты и оборудование",
        "otdelochnye_materialy": "Отделочные и облицовочные материалы",
        "okna_dveri": "Окна / двери / балконы / зеркала",
        "pilomaterialy": "Пиломатериалы",
        "elektrika": "Электрика",
        "otoplenie": "Отопление",
        "stroitelnie_smesi": "Строительные смеси",
        "krovlja": "Кровля",
        "kladochnie_materialy": "Кладочные материалы",
        "stroitelnoe_oborudovanie": "Строительное оборудование",
        "elementy_krepeja": "Элементы крепежа",
        "metalloprokati": "Металлопрокат / арматура",
        "schetchiki": "Счетчики",
        "stroitelnaia_khimia": "Строительная химия",
        "zhelezobeton": "Железобетонные изделия",
        "dorozhnye_materialy": "Дорожные материалы",
        "lakokrasochnye_materialy": "Лакокрасочные материалы",
        "pesok_shcheben": "Песок, щебень, отсев",
        "ventilyacia": "Вентиляция",
        "prochie_tovary": "Прочие товары для строительства и ремонта"
    },
    "prokat_tovarov": {
        "all": "Посмотреть все объявления в Аренда и прокат товаров",
        "spec_tehnika": "Аренда и услуги спецтехники",
        "instrumenty_oborudovanie": "Аренда инструментов и оборудования",
        "transport": "Аренда транспортных средств",
        "avto": "Аренда авто",
        "meropriyatiya": "Аренда товаров для мероприятий и отдыха",
        "elektronika": "Прокат электроники",
        "detskie_tovary": "Аренда детских товаров",
        "prochie_tovary": "Аренда прочих товаров"
    },
    "nedvizhimost": {
        "all": "Посмотреть все объявления в Недвижимость",
        "posutochnaya": "Посуточная аренда жилья",
        "arenda_kvartir": "Аренда квартир долгосрочно",
        "arenda_domov": "Аренда домов долгосрочно",
        "arenda_komnat": "Аренда комнат долгосрочно",
        "prodazha_kvartir": "Продажа квартир",
        "zemlya": "Земля",
        "prodazha_domov": "Продажа домов",
        "kommercheskie": "Коммерческие помещения",
        "prodazha_komnat": "Продажа комнат",
        "garazhi": "Гаражи/стоянки",
        "obmen": "Обмен",
        "zarubezhnaya": "Зарубежная недвижимость"
    },
    "elektronika": {
        "all": "Посмотреть все объявления в Электроника",
        "telefony": "Телефоны и аксессуары",
        "kompyutery": "Компьютеры и комплектующие",
        "foto_video": "Фото / видео",
        "tv": "Тв / видеотехника",
        "audio": "Аудиотехника",
        "igry": "Игры и игровые приставки",
        "planshety": "Планшеты / эл. книги и аксессуары",
        "noutbuki": "Ноутбуки и аксессуары",
        "tehnika_dlya_doma": "Техника для дома",
        "tehnika_dlya_kukhni": "Техника для кухни",
        "klimat": "Климатическое оборудование",
        "individualnyy_ukhod": "Индивидуальный уход",
        "aksessuary": "Аксессуары и комплектующие",
        "prochaya_elektronika": "Прочая электроника",
        "remont_tehniki": "Ремонт и обслуживание техники"
    },
    "dom_i_sad": {
        "all": "Посмотреть все объявления в Дом и сад",
        "kanc_tovary": "Канцтовары / расходные материалы",
        "mebel": "Мебель",
        "produkty": "Продукты питания / напитки",
        "predmety_interera": "Предметы интерьера",
        "komnatnye_rasteniya": "Комнатные растения",
        "posuda": "Посуда / кухонная утварь",
        "sadovy_inventar": "Садовый инвентарь",
        "sad_ogorod": "Сад / огород",
        "hozyainstvennyye": "Хозяйственный инвентарь/бытовая химия",
        "prochie_tovary": "Прочие товары для дома"
    },
    "rabota": {
        "all": "Посмотреть все объявления в Работа",
        "roznichnaya": "Розничная торговля / продажи / закупки",
        "transport_logistika": "Транспорт / Логистика / Склад",
        "stroitelstvo_otdelochnye": "Строительство / Отделочные работы",
        "arhitektura": "Архитектура",
        "banki_finansy": "Банки / Финансы / Страхование",
        "finansy_bukhgalteriya": "Финансы / бухгалтерия / экономика",
        "yuristy": "Юристы / адвокаты / нотариусы",
        "okhrana": "Охрана / безопасность",
        "domashniy_personal": "Домашний персонал / Сервис и быт",
        "krasota_fitnes": "Красота / фитнес / спорт",
        "gostinitsy": "Гостиницы / туризм / отдых",
        "bary_restorany": "Бары / рестораны / кафе",
        "obrazovanie": "Образование / Наука / Перевод",
        "kulturnoe_iskusstvo": "Культура / искусство / развлечения",
        "medicina": "Медицина / фармацевтика",
        "internet_it": "Интернет / IT / компьютеры / телекоммуникации",
        "marketing": "Маркетинг / Реклама / PR",
        "proizvodstvo": "Производство / Рабочие специальности",
        "administrativny": "Административный персонал",
        "hr": "HR / Управление персоналом",
        "stalazh": "Начало карьеры / стажировка / практика",
        "sto": "СТО / автомойки",
        "top_menedzhment": "Топ-менеджмент / руководство высшего звена",
        "selhoz": "Сельское и лесное хозяйство / Агробизнес / Животноводство",
        "rabota_za_rubezhom": "Работа за рубежом",
        "inzhener": "Инженеры",
        "klientskiy_servis": "Клиентский сервис",
        "drugie_sfery": "Другие сферы деятельности"
    },
    "moda_i_stil": {
        "all": "Посмотреть все объявления в Мода и стиль",
        "zhenskaya_odezhda": "Женская одежда",
        "zhenskoe_bele": "Женское белье, купальники",
        "zhenskaya_obuv": "Женская обувь",
        "beremennye": "Одежда для беременных",
        "muzhskaya_odezhda": "Мужская одежда",
        "golovnie_ubory": "Головные уборы",
        "muzhskaya_obuv": "Мужская обувь",
        "muzhskoye_bele": "Мужское белье и плавки",
        "svadba": "Для свадьбы",
        "moda_raznoe": "Мода разное",
        "aksessuary": "Аксессуары",
        "naruchnye_chasy": "Наручные часы",
        "podarki": "Подарки",
        "tovary_dlya_krasoty": "Товары для красоты и здоровья",
        "specodezhda": "Спецодежда и спецобувь"
    },
    "detskiy_mir": {
        "all": "Посмотреть все объявления в Детский мир",
        "detskaya_odezhda": "Детская одежда",
        "detskaya_obuv": "Детская обувь",
        "detskie_kolyaski": "Детские коляски",
        "detskie_avtokresla": "Детские автокресла",
        "detskaya_mebel": "Детская мебель",
        "igrushki": "Игрушки",
        "detskiy_transport": "Детский транспорт",
        "tovary_dlya_kormleniya": "Товары для кормления",
        "tovary_dlya_shkolnikov": "Товары для школьников",
        "prochie_detskie": "Прочие детские товары"
    },
    "hobbi_otdyh_sport": {
        "all": "Посмотреть все объявления в Хобби, отдых и спорт",
        "antikvariat": "Антиквариат / коллекции",
        "muzykalnye_instrumenty": "Музыкальные инструменты",
        "drugoe": "Другое",
        "sport_otdyh": "Спорт / отдых",
        "knigi_jurnaly": "Книги / журналы",
        "cd_dvd": "CD / DVD / пластинки / кассеты",
        "bilety": "Билеты",
        "poputchiki": "Поиск попутчиков",
        "gruppa_muzykantov": "Поиск групп / музыкантов"
    },
    "uslugi": {
        "all": "Посмотреть все объявления в Услуги",
        "razvlecheniya": "Развлечения",
        "krasota_i_zdorove": "Красота и здоровье",
        "dlya_biznesa": "Для бизнеса",
        "avto_uslugi": "Автоуслуги",
        "bytovye_uslugi": "Бытовые услуги",
        "perevozki_skladskie_uslugi": "Перевозки и складские услуги",
        "remont_obsluzhivanie_tehniki": "Ремонт и обслуживание техники",
        "remont_i_stroitelstvo": "Ремонт и строительство",
        "uborka": "Уборка",
        "okhrana_bezopasnost": "Охрана / безопасность",
        "delovye_uslugi": "Деловые услуги",
        "obuchenie_kursy_repetitorstvo": "Обучение / курсы / репетиторство",
        "studiya_zvukozapisi": "Студии звукозаписи",
        "foto_video": "Фото- и видеосъемка",
        "turizm_imigratsiya": "Туризм / иммиграция",
        "setevoy_marketing": "Сетевой маркетинг",
        "uslugi_dlya_zhivotnyh": "Услуги для животных",
        "prochie_uslugi": "Прочие услуги"
    }
}
